//! A controlled weapon/support interaction checked against the separate bundled
//! DLL host. These expected values are never generated by the Rust evaluator.
use poe_optimizer_core::{
    EvaluationSnapshot,
    coverage::{SkillOrigin, SkillResolution},
    evaluation::EvaluationResult,
    metrics::{ActorScope, MeasurementValue, MetricUnit},
    options::{EvaluationOptions, Scalar, SkillSelection},
};
use serde_json::Value;
use std::{fs, path::PathBuf, process::Command};

fn root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn close(label: &str, actual: f64, expected: f64) {
    let tolerance = 1e-8_f64.max(expected.abs() * 1e-9);
    assert!(
        actual.is_finite() && (actual - expected).abs() <= tolerance,
        "{label}: actual {actual}, independent reference {expected}, tolerance {tolerance}"
    );
}

fn evaluate_case(name: &str, smithing: bool, brutality: bool) -> f64 {
    let directory = root().join("tests/fixtures/calibration");
    let reference: Value = serde_json::from_slice(
        &fs::read(directory.join(format!("{name}.reference.json"))).unwrap(),
    )
    .unwrap();
    assert_eq!(reference["schema_version"], 1);
    assert_eq!(
        reference["method"],
        "bundled-dll-independent-host-direct-main-attack-v1"
    );
    assert_eq!(reference["runtime"]["jit_version"], "LuaJIT 2.1.1784580905");
    assert_eq!(reference["runtime"]["architecture"], "x64");
    assert_eq!(reference["comparison"]["absolute_tolerance"], 1e-8);
    assert_eq!(reference["comparison"]["relative_tolerance"], 1e-9);
    assert_eq!(
        reference["provenance"]["upstream_revision"],
        poe_optimizer_pob::runtime::UPSTREAM_REVISION
    );
    for field in [
        "fixture_sha256",
        "source_manifest_sha256_lf",
        "lua51_dll_sha256",
        "lua_utf8_dll_sha256",
        "driver_source_sha256_lf",
        "driver_executable_sha256",
        "harness_sha256_lf",
        "generator_sha256_lf",
    ] {
        let hash = reference["provenance"][field].as_str().unwrap();
        assert_eq!(hash.len(), 64, "{field}");
        assert!(hash.bytes().all(|byte| byte.is_ascii_hexdigit()));
    }

    let options = EvaluationOptions {
        selection: Some(SkillSelection {
            socket_group: 1,
            active_skill: Some(1),
            minion_skill: None,
        }),
        encounter: None,
    };
    let scratch = tempfile::tempdir().unwrap();
    let options_path = scratch.path().join("options.json");
    fs::write(&options_path, serde_json::to_vec(&options).unwrap()).unwrap();
    let output = Command::new(env!("CARGO_BIN_EXE_poe-optimizer"))
        .current_dir(root())
        .arg("evaluate")
        .arg(directory.join(format!("{name}.xml")))
        .args(["--timeout-seconds", "60", "--raw", "--options"])
        .arg(options_path)
        .output()
        .unwrap();
    assert!(
        output.status.success(),
        "{name}: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let report: Value = serde_json::from_slice(&output.stdout).unwrap();
    assert_eq!(report["schema_version"], 2);
    assert_eq!(
        report["source"]["xml_sha256"],
        reference["provenance"]["fixture_sha256"]
    );
    let result: EvaluationResult = serde_json::from_value(report["evaluation"].clone()).unwrap();
    assert_eq!(result.context.requested, options);
    assert_eq!(result.context.calculation_mode, "MAIN");
    assert_eq!(result.context.enemy_level, 60);
    assert_eq!(
        result.backend.source_fingerprint,
        reference["provenance"]["source_manifest_sha256_lf"]
    );
    assert!(result.diagnostic_only);
    assert_eq!(result.attachments.len(), 1);
    let raw: EvaluationSnapshot = serde_json::from_str(&result.attachments[0].content).unwrap();
    assert_eq!(raw.player.skill_id.as_deref(), Some("Melee1HMacePlayer"));
    assert!(raw.player.has_hit_damage);
    assert!(raw.minion.is_none());
    assert_eq!(result.build.class_name, "Warrior");
    assert_eq!(result.build.ascendancy_name, "None");
    assert_eq!(result.build.level, 60);
    assert_eq!(result.build.allocated_nodes, [47175]); // Implicit Warrior start only.
    for (key, value) in reference["config"].as_object().unwrap() {
        let expected: Scalar = serde_json::from_value(value.clone()).unwrap();
        assert_eq!(
            result.context.config_inputs.get(key),
            Some(&expected),
            "{key}"
        );
    }
    let metrics = reference["metrics"].as_object().unwrap();
    assert_eq!(
        metrics.len(),
        25,
        "Review a change to attack reference coverage"
    );
    for (metric, expected) in metrics {
        close(
            &format!("{name}.{metric}"),
            *raw.player
                .metrics
                .get(metric)
                .unwrap_or_else(|| panic!("Missing {metric}")),
            expected.as_f64().unwrap(),
        );
    }
    let attack = &reference["attack"];
    assert_eq!(
        attack["weapon_name"],
        if smithing {
            "Smithing Hammer"
        } else {
            "Wooden Club"
        }
    );
    assert_eq!(attack["weapon_type"], "One Hand Mace");
    assert_eq!(attack["weapon_quality"], 0);
    assert_eq!(attack["skill_level"], 1);
    assert!(
        raw.player.metrics["Str"] >= attack["weapon_requirements"]["strength"].as_f64().unwrap()
    );
    assert_eq!(
        attack["weapon_requirements"]["strength"],
        if smithing { 11 } else { 0 }
    );
    for (raw_key, reference_key) in [
        ("PhysicalMinOnWeapon 1", "physical_min"),
        ("PhysicalMaxOnWeapon 1", "physical_max"),
        ("Speed", "attack_rate"),
    ] {
        close(
            raw_key,
            raw.player.metrics[raw_key],
            attack[reference_key].as_f64().unwrap(),
        );
    }
    let supports = attack["applied_support_ids"].as_array().unwrap();
    assert_eq!(supports.len(), usize::from(brutality));
    if brutality {
        assert_eq!(supports[0], "SupportBrutalityPlayer");
        assert_eq!(raw.player.metrics["FireStoredCombinedAvg"], 0.0);
    } else if smithing {
        assert!(raw.player.metrics["FireStoredCombinedAvg"] > 0.0);
    }
    let coverage = &result.coverage;
    assert_eq!(coverage.unresolved_entry_count, 0);
    assert_eq!(coverage.groups.len(), 1);
    let group = &coverage.groups[0];
    assert_eq!(group.provenance.kind, SkillOrigin::Manual);
    assert_eq!(group.gems.len(), 1 + usize::from(brutality));
    assert_eq!(group.gems[0].skill_id.as_deref(), Some("Melee1HMacePlayer"));
    for gem in &group.gems {
        assert!(gem.enabled);
        assert_eq!(gem.resolution, SkillResolution::ResolvedGem);
        assert_eq!(gem.level, Some(1.0));
        assert_eq!(gem.quality, Some(0.0));
    }
    if brutality {
        assert_eq!(
            group.gems[1].skill_id.as_deref(),
            Some("SupportBrutalityPlayer")
        );
        assert_eq!(group.gems[1].is_support, Some(true));
    }
    let selected = coverage.selected_player.as_ref().unwrap();
    assert_eq!(selected.skill_id.as_deref(), Some("Melee1HMacePlayer"));
    assert_eq!(selected.group_index, Some(1));
    assert_eq!(selected.gem_index, Some(1));
    assert!(!selected.synthesized_default_attack);
    assert!(!selected.show_average);
    assert_eq!(coverage.full_dps.included_group_count, 1);
    assert!(coverage.full_dps.selected_group_included);

    let measurement = |id: &str| {
        result
            .measurements
            .iter()
            .find(|metric| metric.query.actor == ActorScope::Player && metric.query.id == id)
            .unwrap()
    };
    let dps = measurement("selected_hit_dps");
    assert_eq!(dps.unit, MetricUnit::DamagePerSecond);
    let actual = dps.value.finite().expect("Attack DPS is available");
    close(
        "typed selected hit DPS",
        actual,
        metrics["TotalDPS"].as_f64().unwrap(),
    );
    // PoB keeps attack averages in MainHand/OffHand. A future mapping must define
    // their combined meaning; the adapter must not silently invent that value.
    assert!(!raw.player.metrics.contains_key("AverageHit"));
    assert_eq!(measurement("selected_average_hit").unit, MetricUnit::Damage);
    assert!(matches!(
        &measurement("selected_average_hit").value,
        MeasurementValue::Unavailable { reason } if !reason.is_empty()
    ));
    assert!(attack["main_hand"]["AverageHit"].as_f64().unwrap() > 0.0);
    actual
}

#[test]
fn weapon_preference_reverses_with_brutality_and_matches_independent_references() {
    let wooden = evaluate_case("mace-wooden", false, false);
    let smithing = evaluate_case("mace-smithing", true, false);
    let wooden_brutality = evaluate_case("mace-wooden-brutality", false, true);
    let smithing_brutality = evaluate_case("mace-smithing-brutality", true, true);
    assert!(
        smithing > wooden,
        "Fire damage favors the Smithing Hammer without Brutality"
    );
    assert!(
        wooden_brutality > smithing_brutality,
        "Removing fire reverses the weapon ranking"
    );
    assert!(
        wooden_brutality > wooden,
        "Brutality improves the physical-only weapon"
    );
    assert!(
        smithing_brutality < smithing,
        "Brutality reduces the mixed-damage weapon's DPS"
    );
    // This cross difference is nonzero: equipment and support cannot be scored
    // independently and then added to predict the joint choice.
    close(
        "weapon/support interaction",
        smithing_brutality - wooden_brutality - smithing + wooden,
        -10.404968,
    );
}
